# Generated by Django 6.0.7 on 2026-08-05 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de orden')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='nombre del cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(max_length=30, verbose_name='teléfono')),
                ('direccion_entrega', models.CharField(max_length=255, verbose_name='dirección de entrega')),
                ('ciudad_entrega', models.CharField(max_length=100, verbose_name='ciudad')),
                ('referencia_entrega', models.CharField(blank=True, max_length=255, verbose_name='referencia de entrega')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='subtotal')),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='envío')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('moneda', models.CharField(default='COP', max_length=3, verbose_name='moneda')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_tienda', to='clientes.cliente', verbose_name='cliente registrado')),
            ],
            options={
                'verbose_name': 'Orden de tienda',
                'verbose_name_plural': 'Órdenes de tienda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='estado nuevo')),
                ('comentario', models.TextField(blank=True, verbose_name='comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tienda.orden', verbose_name='orden')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Cambio de estado de orden',
                'verbose_name_plural': 'Historial de estados de órdenes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre del producto')),
                ('imagen', models.CharField(blank=True, max_length=300, verbose_name='imagen')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='precio unitario')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.orden', verbose_name='orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_orden', to='almacen.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Item de orden',
                'verbose_name_plural': 'Items de orden',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PagoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('paypal', 'PayPal'), ('billetera', 'Billetera / app')], max_length=20, verbose_name='método')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto')),
                ('moneda', models.CharField(default='COP', max_length=3, verbose_name='moneda')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='referencia del proveedor')),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4, verbose_name='últimos 4 dígitos')),
                ('marca_tarjeta', models.CharField(blank=True, max_length=30, verbose_name='marca de tarjeta')),
                ('detalle', models.JSONField(blank=True, default=dict, verbose_name='detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tienda.orden', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Pago de tienda',
                'verbose_name_plural': 'Pagos de tienda',
                'ordering': ['-created_at'],
            },
        ),
    ]
