# Generated by Django 6.0.7 on 2026-08-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='moneda',
            field=models.CharField(default='DOP', max_length=3, verbose_name='moneda'),
        ),
        migrations.AlterField(
            model_name='pagotienda',
            name='moneda',
            field=models.CharField(default='DOP', max_length=3, verbose_name='moneda'),
        ),
    ]
