# Generated by Django 6.0.8 on 2026-08-20 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_orden_moneda_alter_pagotienda_moneda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='documento',
            field=models.CharField(blank=True, max_length=30, verbose_name='documento / RNC'),
        ),
        migrations.AddField(
            model_name='orden',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='orden',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='sector'),
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_tienda', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
