# Generated by Django 6.0.7 on 2026-08-05 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
        ('materiales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitud'),
        ),
        migrations.CreateModel(
            name='InstalacionEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='estado nuevo')),
                ('comentario', models.TextField(blank=True, verbose_name='comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='instalaciones.instalacion', verbose_name='instalación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Cambio de estado de instalación',
                'verbose_name_plural': 'Historial de estados de instalaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MaterialInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_instalacion', to='instalaciones.instalacion', verbose_name='instalación')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_instalacion', to='materiales.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'Material de instalación',
                'verbose_name_plural': 'Materiales de instalación',
                'ordering': ['id'],
            },
        ),
    ]
