# Generated by Django 6.0.7 on 2026-08-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('cambio_estado', 'Cambio de estado'), ('iniciar_sesion', 'Iniciar sesión'), ('cerrar_sesion', 'Cerrar sesión'), ('otro', 'Otro')], max_length=30, verbose_name='acción')),
                ('model_name', models.CharField(max_length=100, verbose_name='modelo')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='descripción del objeto')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('imagen', models.ImageField(upload_to='evidencias/%Y/%m/', verbose_name='imagen')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('fase', models.CharField(choices=[('antes', 'Antes'), ('durante', 'Durante'), ('despues', 'Después')], default='despues', max_length=20, verbose_name='fase')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'Evidencia fotográfica',
                'verbose_name_plural': 'Evidencias fotográficas',
                'ordering': ['-created_at'],
            },
        ),
    ]
