# Generated by Django 6.0.7 on 2026-10-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_firmadigital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('cambio_estado', 'Cambio de estado'), ('iniciar_sesion', 'Iniciar sesión'), ('cerrar_sesion', 'Cerrar sesión'), ('cambiar_contraseña', 'Cambiar contraseña'), ('restablecer_contraseña', 'Restablecer contraseña'), ('otro', 'Otro')], max_length=30, verbose_name='acción'),
        ),
    ]
