# Generated by Django 6.0.7 on 2026-08-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clientes', '0001_initial'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=20, verbose_name='tipo')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('proxima_fecha', models.DateField(blank=True, null=True, verbose_name='próxima fecha de mantenimiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('trabajo_realizado', models.TextField(blank=True, verbose_name='trabajo realizado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='clientes.cliente', verbose_name='cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipos.equipo', verbose_name='equipo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='accounts.tecnico', verbose_name='técnico responsable')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
