# Generated by Django 6.0.7 on 2026-08-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Tipo de equipo',
                'verbose_name_plural': 'Tipos de equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='número de serie')),
                ('capacidad', models.CharField(blank=True, help_text='Ej: 12000 BTU, 1.5 HP, 10 m³', max_length=50, verbose_name='capacidad')),
                ('refrigerante', models.CharField(blank=True, help_text='Ej: R-410A, R-22, R-134a', max_length=50, verbose_name='refrigerante')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('instalado', 'Instalado'), ('averiado', 'Averiado'), ('en_reparacion', 'En reparación'), ('retirado', 'Retirado')], default='disponible', max_length=20, verbose_name='estado')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='fecha de instalación')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Sala principal, bodega 2', max_length=150, verbose_name='ubicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente', verbose_name='cliente propietario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipos.tipoequipo', verbose_name='tipo de equipo')),
            ],
            options={
                'verbose_name': 'Equipo de refrigeración',
                'verbose_name_plural': 'Equipos de refrigeración',
                'ordering': ['marca', 'modelo'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'numero_serie'), name='uniq_equipo_serie_por_cliente')],
            },
        ),
    ]
