# Generated by Django 6.0.7 on 2026-08-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='garantia_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Meses de garantía desde la fecha de instalación del equipo.', null=True, verbose_name='garantía (meses)'),
        ),
    ]
