# Generated by Django 6.0.7 on 2026-08-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo_solicitado', models.CharField(max_length=150, verbose_name='tipo de equipo solicitado')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción del requerimiento')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('reprogramada', 'Reprogramada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='fecha de solicitud')),
                ('fecha_deseada', models.DateField(blank=True, null=True, verbose_name='fecha deseada')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Solicitud de instalación',
                'verbose_name_plural': 'Solicitudes de instalación',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
