# Generated by Django 6.0.7 on 2026-09-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinstalacion',
            name='tipo_solicitud',
            field=models.CharField(choices=[('instalacion', 'Instalación'), ('reparacion', 'Reparación'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='tipo de solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudinstalacion',
            name='tipo_equipo_solicitado',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='equipo solicitado'),
        ),
    ]
