# Generated by Django 6.0.7 on 2026-08-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('icono', models.CharField(blank=True, help_text='Nombre del ícono de Material Symbols usado en la vitrina', max_length=50, verbose_name='ícono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('imagen', models.CharField(blank=True, help_text='Ruta del asset (ej: /assets/img/productos/tuberia.svg)', max_length=300, verbose_name='imagen')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = "Consultar precio"', max_digits=12, null=True, verbose_name='precio')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='almacen.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
