# Generated by Django 6.0.7 on 2026-08-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, verbose_name='en oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio promocional mostrado en la vitrina cuando el producto está en oferta.', max_digits=12, null=True, verbose_name='precio de oferta'),
        ),
    ]
