# Generated by Django 6.0.7 on 2026-08-10 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, verbose_name='hash del token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('expires_at', models.DateTimeField(verbose_name='expira el')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Token de recuperación',
                'verbose_name_plural': 'Tokens de recuperación',
                'ordering': ['-created_at'],
            },
        ),
    ]
