# Generated by Django 6.0.7 on 2026-10-06 20:02

import apps.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_supervisor_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=apps.accounts.storage.SupabaseStorage(), upload_to='fotos_perfil/', verbose_name='foto de perfil'),
        ),
    ]
