# Generated by Django 6.0.7 on 2026-08-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clientes', '0001_initial'),
        ('equipos', '0001_initial'),
        ('materiales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de orden')),
                ('tipo_servicio', models.CharField(choices=[('instalacion', 'Instalación'), ('reparacion', 'Reparación'), ('mantenimiento_preventivo', 'Mantenimiento preventivo'), ('mantenimiento_correctivo', 'Mantenimiento correctivo'), ('diagnostico', 'Diagnóstico'), ('revision', 'Revisión')], default='reparacion', max_length=40, verbose_name='tipo de servicio')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('problema_reportado', models.TextField(blank=True, verbose_name='problema reportado')),
                ('diagnostico', models.TextField(blank=True, verbose_name='diagnóstico')),
                ('trabajo_realizado', models.TextField(blank=True, verbose_name='trabajo realizado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_proceso', 'En proceso'), ('reprogramada', 'Reprogramada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones técnicas')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de asignación')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente', verbose_name='cliente')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='equipos.equipo', verbose_name='equipo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='accounts.tecnico', verbose_name='técnico asignado')),
            ],
            options={
                'verbose_name': 'Orden de servicio',
                'verbose_name_plural': 'Órdenes de servicio',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='materiales.material', verbose_name='material')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_utilizados', to='servicios.ordenservicio', verbose_name='orden de servicio')),
            ],
            options={
                'verbose_name': 'Material utilizado',
                'verbose_name_plural': 'Materiales utilizados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoOrdenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='estado nuevo')),
                ('comentario', models.TextField(blank=True, verbose_name='comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='servicios.ordenservicio', verbose_name='orden de servicio')),
            ],
            options={
                'verbose_name': 'Cambio de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-fecha'],
            },
        ),
    ]
