# Generated by Django 6.0.7 on 2026-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoordenlog',
            name='estado_anterior',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='estado anterior'),
        ),
    ]
