# Generated by Django 6.0.7 on 2026-08-09 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clientes', '0002_alter_cliente_tipo_documento'),
        ('servicios', '0002_alter_estadoordenlog_estado_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de visita')),
                ('fecha', models.DateField(verbose_name='fecha de la visita')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='estado')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo de la visita')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección de la visita')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='clientes.cliente', verbose_name='cliente')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='servicios.ordenservicio', verbose_name='orden de servicio')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='accounts.tecnico', verbose_name='técnico asignado')),
            ],
            options={
                'verbose_name': 'Visita técnica',
                'verbose_name_plural': 'Visitas técnicas',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
