# Generated by Django 6.0.7 on 2026-08-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('instalaciones', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(help_text='Valor entre 1 y 5', verbose_name='calificación')),
                ('comentario', models.TextField(blank=True, verbose_name='comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='clientes.cliente', verbose_name='cliente')),
                ('instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='instalaciones.instalacion', verbose_name='instalación')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='servicios.ordenservicio', verbose_name='orden de servicio')),
            ],
            options={
                'verbose_name': 'Evaluación del servicio',
                'verbose_name_plural': 'Evaluaciones del servicio',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('orden__isnull', False)), fields=('cliente', 'orden'), name='uniq_evaluacion_orden')],
            },
        ),
    ]
