# Generated by Django 6.0.7 on 2026-08-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('persona', 'Persona natural'), ('empresa', 'Empresa')], default='persona', max_length=20, verbose_name='tipo')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('apellidos', models.CharField(blank=True, max_length=150, verbose_name='apellidos')),
                ('tipo_documento', models.CharField(choices=[('cc', 'Cédula de ciudadanía'), ('nit', 'NIT'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='cc', max_length=20, verbose_name='tipo de documento')),
                ('documento_numero', models.CharField(max_length=30, unique=True, verbose_name='número de documento')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='teléfono alternativo')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='DireccionInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(default='Dirección principal', max_length=100, verbose_name='etiqueta')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='referencia')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitud')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Dirección de instalación',
                'verbose_name_plural': 'Direcciones de instalación',
                'ordering': ['-principal', 'id'],
            },
        ),
    ]
