# Generated by Django 6.0.7 on 2026-08-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('cc', 'Cédula'), ('pasaporte', 'Pasaporte'), ('rnc', 'RNC (empresa)'), ('nit', 'NIT'), ('otro', 'Otro')], default='cc', max_length=20, verbose_name='tipo de documento'),
        ),
    ]
