# Generated by Django 6.0.7 on 2026-08-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='categoría')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('litro', 'Litro'), ('galon', 'Galón'), ('kilogramo', 'Kilogramo'), ('libra', 'Libra'), ('paquete', 'Paquete')], default='unidad', max_length=20, verbose_name='unidad de medida')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cantidad disponible')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='stock mínimo')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='materiales.material', verbose_name='material')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
